addSbtPlugin("com.eed3si9n"              % "sbt-assembly"      % "0.14.9")
addSbtPlugin("com.github.sbt"            % "sbt-eclipse"  % "6.0.0")
addSbtPlugin("com.github.sbt"            % "sbt-git"      % "2.0.1")
addSbtPlugin("com.jsuereth"              % "sbt-pgp"      % "1.1.0")
addSbtPlugin("io.gatling"                % "gatling-sbt"       % "3.0.0")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"      % "0.4.2")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"      % "2.4.0")
